#!/usr/bin/env php
<?php

$folders = [
    '/storage',
];

foreach ($folders as $folder) {
    if (!file_exists(__DIR__ . $folder)) {
        mkdir(__DIR__ . $folder, 0700);
    }
}

require_once __DIR__.'/vendor/autoload.php';
require_once __DIR__ . '/config/config.php';

use MiniRest\Console\RunMakeCommand;
use Symfony\Component\Console\Application;
use MiniRest\Console\RunServeCommand;

if (PHP_OS_FAMILY === 'Linux') {
    shell_exec('chmod +x ' . __FILE__);
}

if (strncasecmp(PHP_OS, 'WIN', 3) === 0) {
    $command = 'icacls "' . __FILE__ . '" /grant Everyone:RX';
    shell_exec($command);
}



$app = new Application;
$app->add(new RunServeCommand());
$app->add(new RunMakeCommand());
$app->run();